spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.23.100:8848
server:
  port: 8081

logging:
  config: classpath:logback.xml

management:
  endpoints:
    web:
      exposure:
        include: '*'